routes/web.php
<?php

use App\Site;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// sites
Route::group(['prefix' => 'sites', 'as' => 'sites.'], function () {
  Route::post('{id}/files/save', 'SiteController@saveFiles')->name('files.save');
  Route::delete('{id}/files/{file_id}/delete', 'SiteController@deleteFile')->name('files.destroy');
  Route::post('{id}/departments/save', 'SiteController@saveDepartment')->name('departments.save');
  Route::delete('{id}/departments/{dept_id}/delete', 'SiteController@deleteDepartment')->name('departments.destroy');
  Route::post('{id}/initiatives/save', 'SiteController@saveInitiative')->name('initiatives.save');
  Route::put('{id}/initiatives/{init_id}/update', 'SiteController@updateInitiative')->name('initiatives.update');
  Route::delete('{id}/initiatives/{init_id}/delete', 'SiteController@deleteInitiative')->name('initiatives.destroy');
});
Route::resource('sites', 'SiteController');

// site specific routes
Route::group(['prefix' => '{site}'], function () {
  Route::get('/', 'SiteController@show')->name('index');
  Route::get('contact', 'SiteController@contact')->name('contact');
  Route::post('contact', 'SiteController@contactSend')->name('contact.send');
  Route::get('admin', 'SiteController@admin')->name('admin');

  // pages (editing)
  Route::put('pages/order', 'PageController@updateOrder')->name('pages.order');
  Route::resource('pages', 'PageController');

  // project sets
  Route::group(['prefix' => 'project-sets', 'as' => 'project-sets.'], function() {
    Route::get('{id}/set', 'ProjectSetController@setSession')->name('set');
  });
  Route::resource('project-sets', 'ProjectSetController');

  // questions and answers
  Route::post('{id}/extend', 'QuestionController@questionExtension')->name('questions.questionExtension');

  // Route::get('{id}/extend/done','QuestionController@questionExtensionDone');
  Route::resource('questions', 'QuestionController');

  Route::resource('answers', 'AnswerController');

  // users
  Route::resource('users', 'UserController');
  Route::put('users/site/update', 'UserController@updateSite')->name('users.site.update');
  Route::get('directory', 'UserController@directory')->name('users.directory');
  Route::group(['prefix' => 'board/apply'], function() {
    Route::get('/', 'UserController@apply')->name('users.apply');
    Route::post('/', 'UserController@applyStore')->name('users.apply.store');
    Route::get('index', 'UserController@applyIndex')->name('users.apply.index');
    Route::get('{id}/view', 'UserController@applyView')->name('users.apply.view');
    Route::get('{id}/confirm', 'UserController@confirm')->name('users.apply.confirm');
    Route::get('{id}/edit', 'UserController@applyEdit')->name('users.apply.edit');
    Route::put('{id}', 'UserController@applyUpdate')->name('users.apply.update');
    Route::put('{id}/save', 'UserController@applySave')->name('users.apply.save');
    Route::put('{id}/accept', 'UserController@applyAccept')->name('users.apply.accept');
    Route::delete('{id}/destroy', 'UserController@applyDestroy')->name('users.apply.destroy');
  });

  Route::group(['prefix' => '{project_set}'], function() {
    // custom project routes
    Route::group(['prefix' => 'projects', 'as' => 'projects.'], function () {
      Route::get('start', 'ProjectController@createStart')->name('start');
      Route::put('save', 'ProjectController@save')->name('save');
      Route::put('approve', 'ProjectController@approve')->name('approve');
      Route::get('review', 'ProjectController@review')->name('review');
      Route::get('admin', 'ProjectController@admin')->name('admin.index');
      Route::get('{id}/admin', 'ProjectController@adminEdit')->name('admin.edit');
      Route::get('{id}/confirm', 'ProjectController@confirm')->name('apply.confirm');
      Route::get('{id}/approve', 'ProjectController@showApprove')->name('apply.approve');
      Route::get('{id}/full', 'ProjectController@full')->name('full');
      Route::post('{id}/remind', 'ProjectController@remind')->name('remind');
      Route::get('{id}/files', 'ProjectController@files')->name('files');
      Route::post('{id}/files/save', 'ProjectController@saveFile')->name('files.save');
      Route::delete('files/{id}/delete', 'ProjectController@deleteFile')->name('files.destroy');
      Route::put('files/{id}/move', 'ProjectController@moveFile')->name('files.move');
      Route::get('{id}/revisions', 'ProjectController@revisions')->name('revisions');
      Route::get('{id}/budgets', 'ProjectController@budgets')->name('budgets');
      Route::get('{id}/notifications', 'ProjectController@notifications')->name('notifications');
      Route::get('{id}/questions', 'ProjectController@questions')->name('questions');
      Route::get('{id}/comments', 'ProjectController@comments')->name('comments');
      Route::post('{id}/comments/save', 'ProjectController@saveComment')->name('comments.save');
    });
    // project resource routes
    Route::resource('projects', 'ProjectController');

    // progress reports
    Route::group(['prefix' => 'progress', 'as' => 'progress.'], function() {
      Route::get('start', 'ProgressReportController@createStart')->name('start');
      Route::get('{id}/review', 'ProgressReportController@review')->name('review');
      Route::get('{id}/admin', 'ProgressReportController@adminEdit')->name('admin');
      Route::post('send', 'ProgressReportController@send')->name('send');
      Route::put('{id}/move', 'ProgressReportController@move')->name('move');
    });
    Route::resource('progress', 'ProgressReportController');

    // pars
    Route::group(['prefix' => 'pars', 'as' => 'pars.'], function() {
      Route::get('start', 'ParController@createStart')->name('start');
      Route::get('admin', 'ParController@admin')->name('admin.index');
      Route::get('{id}/review', 'ParController@review')->name('review');
      Route::get('{id}/advice', 'ParController@advice')->name('advice');
      Route::put('{id}/advice/update', 'ParController@updateAdvice')->name('advice.update');
      Route::get('{id}/advice/review', 'ParController@reviewAdvice')->name('advice.review');
      Route::get('{id}/vp', 'ParController@vp')->name('vp');
      Route::put('{id}/vp/update', 'ParController@updateVp')->name('vp.update');
      Route::get('{id}/vp/review', 'ParController@reviewVp')->name('vp.review');
      Route::get('{id}/approve', 'ParController@approve')->name('approve');
      Route::get('{id}/admin/edit', 'ParController@adminEdit')->name('admin.edit');
    });
    Route::resource('pars', 'ParController');
  });

  // login
  Route::get('login', 'UserController@login')->name('login');

  // handle redirects from webauth
  Route::get('webauth/redirect', ['as' => 'guest.login.redirect', 'uses' => 'WebauthController@redirect']);

  // this goes last to not catch anything important
  Route::get('/{any}', 'PageController@showBySlug')->where('any', '.*');
});

app/Par.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Par extends Model
{
    // get the project this PAR belongs to
    public function project()
    {
        return $this->belongsTo('App\Project');
    }

    // get the files for this PAR
    public function files()
    {
        return $this->morphMany('App\File', 'fileable');
    }

    // get the questions for this PAR
    public function questions()
    {
        return $this->morphMany('App\Question', 'questionable');
    }

    // full url for supporting file
    public function getFileSupportURLAttribute()
    {
        return getFileUrl($this->files, 2);
    }

    // full url for advice file
    public function getFileAdviceURLAttribute()
    {
        return getFileUrl($this->files, 6);
    }

    // if there is no board id in the db, auto generate one. use 'T' to indicate temporary
    public function getBoardIdAttribute($value)
    {
        return isset($value) ? $value : site()->abbreviation . '-T' . $this->id;
    }

    // clean up relationships on delete
    public function delete()
    {
        deleteItems($this->files);
        deleteItems($this->questions);
        Parent::delete();
    }
}

resources/views/project/comments.blade.php
@extends('layouts.app')

@section('breadcrumbs')
  @component('partials.breadcrumbs.project', ['project' => $project])
        <li class="active">Comments</li>
  @endcomponent
@endsection

@section('title')
    Comments
@endsection

@section('content')
    <h3>{{ $project->project_name }}</h3>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Comment Details</h3>
        </div>
        <div class="panel-body">
            @if ($comments->count() == 0)
                <p>No comments on file for this project.</p>
            @else    
                @include('partials.project.comment-list', ['comments' => $comments])
            @endif
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Add New Comment</h3>
        </div>
        <div class="panel-body">
            @include('partials.project.comment', ['parent' => 0])
        </div>
    </div>
@endsection

resources/views/project/index.blade.php
@extends('layouts.app')

@section('breadcrumbs')
  @if ($apply)
    @include('partials.breadcrumbs.create')
  @elseif ($authorized)
    @component('partials.breadcrumbs.default')
      <li class="active">Projects</li>
    @endcomponent
  @else
    @component('partials.breadcrumbs.base')
      <li class="active">Projects</li>
    @endcomponent
  @endif
@endsection

@section('title')
  @if ($apply)
    Apply for Funding
  @else
    {{ $admin ? 'Edit' : 'View' }} Projects
  @endif
@endsection

@section('content')

  @if ($apply)
    <p>Welcome, {{ $netid }}!</p>
    <p>You have the following applications open and available for editing. You may also <a href="{{ route('projects.create', baseRouteParams()) }}">create a new application</a> if you wish.</p>
  @else
    <h4>Which group of funding applications would you like to see?</h4>
    <form role="form" method="GET" action="{{ route($filter_route, baseRouteParams()) }}">
      <div class="row">
        <div class="col-md-2">
          @include('partials.form.filter_select', ['session_group' => 'project-filters', 'name' => 'funding-status', 'label' => 'Funding Status', 'items' => $funding_statuses, 'value' => 'id', 'text' => 'name'])
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <select name="year" class="form-control" onchange="this.form.submit()">
              <option value="-1">Fiscal Year...</option>
              @foreach ($years as $year)
                @if ($year > 0)
                  <option value="{{ $year }}"{{ $year == Session::get('project-filters.year')? ' selected' : ''}}>FY {{ $year+1 }}</option>
                @endif
              @endforeach
            </select>
          </div>
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <select name="project-status" class="form-control" onchange="this.form.submit()">
              <option value="-1">Project Status...</option>
              <option value="0"{{ Session::get('project-filters.project-status') === '0' ? ' selected' : ''}}>Active</option>
              <option value="1"{{ Session::get('project-filters.project-status') === '1' ? ' selected' : ''}}>Archived</option>
            </select>
          </div>
        </div>
        @if ($authorized)
          <div class="col-md-2">
            <div class="form-group">
              <select name="progress-reports" class="form-control" onchange="this.form.submit()">
                <option value="-1">Progress Reports...</option>
                <option value="30"{{ Session::get('project-filters.progress-reports') == 30 ? ' selected' : ''}}>Last 30 Days</option>
                <option value="60"{{ Session::get('project-filters.progress-reports') == 60 ? ' selected' : ''}}>Last 60 Days</option>
                <option value="90"{{ Session::get('project-filters.progress-reports') == 90 ? ' selected' : ''}}>Last 90 Days</option>
                <option value="180"{{ Session::get('project-filters.progress-reports') == 180 ? ' selected' : ''}}>Last 180 Days</option>
                <option value="365"{{ Session::get('project-filters.progress-reports') == 365 ? ' selected' : ''}}>Last 365 Days</option>
              </select>
            </div>
          </div>
          <div class="col-md-3">
            <input type="checkbox" name="admin-projects" value="1"{{ Session::get('project-filters.admin-projects') == 1 ? ' checked' : ''}} onclick="this.form.submit()">
            Administrative Projects
          </div>
        @endif
      </div>
    </form>
  @endif
  <div class="table-responsive">
    <table class="table-dark table-hover table-striped table-condensed{{ $authorized ? ' table-funding' : '' }}">
      <thead>
        <tr>
          @if ($authorized || $apply)
            <th>#</th>
          @endif
          @if (!$apply)
            <th>ID</th>
          @endif
          <th>Project Name</th>
          <th>Department</th>
          <th>Manager</th>
          <th>Initial Year</th>
          <th class="text-right">
            @if ($authorized)
              Request/Years
            @elseif (!$apply)
              Selected Year Funding
            @endif
          </th>
          @if (!$apply)
            <th>Status</th>
            @if ($authorized)
              <th>Public</th>
              <th>Locked</th>
              <th>Withdrawn</th>
              @if ($admin)
                <th></th>
                @if (userIsAdmin())
                  <th></th>
                @endif
                <th></th>
                @if (userIsPower())
                  <th></th>
                @endif
              @endif
            @endif
          @endif
        </tr>
      </thead>
      <tbody>
      @foreach ($projects as $key => $project)
        <tr>
          @if ($authorized || $apply)
            <td>{{ $apply ? $loop->iteration : $project->id }}</td>
          @endif
          @if (!$apply)
            <td>{{ $project->board_id }}</td>
          @endif
          <td><a href="{{ route($apply ? 'projects.edit' : 'projects.show', routeParams(['id' => $project->id])) }}">{{ !empty($project->project_name) ? $project->project_name : 'Untitled' }}</a></td>
          <td>{{ $project->department->name or '' }}</td>
          <td>{{ $project->first_name }} {{ $project->last_name }}</td>
          <td>{{ !empty($project->start_year) ? ('FY' . substr($project->fiscal_year, 2, 2)) : '' }}</td>
          <td class="text-right" style="position: relative;">
            @if ($authorized)
              <a href="#fundingCollapse{{ $project->id }}" role="button" data-toggle="collapse">${{ number_format($project->totalFunding->requested_amount/$project->duration) }}/{{ $project->duration }}</a>
            @elseif (!$apply)
              ${{ number_format($project->selectedYearFunding(Session::get('project-filters.year'))->board_amount) }}
            @endif
          </td>
          @if (!$apply)
            <td>{{ $project->archived ? 'Archived' : 'Active' }}</td>
            @if ($authorized)
              <td>{{ formatBoolean($project->public) }}</td>
              <td>{{ formatBoolean($project->locked) }}</td>
              <td>{{ formatBoolean($project->funding_status_id == 6) }}</td>
              @if ($admin)
                <td>
                  <a class="text-blue30w" href="#" title="Submit Question"
                      data-toggle="modal"
                      data-target="#modalQuestion"
                      data-title="{{ $project->board_id }}"
                      data-project="{{ $project->project_name }}"
                      data-item-type="1"
                      data-item-id="{{ $project->id }}">
                      <span class="glyphicon glyphicon-question-sign">
                  </a>
                </td>
                @if (userIsAdmin())
                  <td>
                    <a class="text-blue30w" href="#" title="Request Progress Report"
                      data-toggle="modal"
                      data-target="#modalRequestReport"
                      data-project="{{ $project->project_name }}"
                      data-name="{{ $project->first_name }} {{ $project->last_name }}"
                      data-director="{{ $project->director_first_name }} {{ $project->director_last_name }}"
                      data-fiscal="{{ $project->fiscal_first_name }} {{ $project->fiscal_last_name }}"
                      data-id="{{ $project->id }}">
                      <span class="glyphicon glyphicon-list-alt">
                    </a>
                  </td>
                @endif
                <td><a class="text-blue30w" href="{{ route('projects.admin.edit', routeParams(['id' => $project->id])) }}" title="Edit Project"><span class="glyphicon glyphicon-pencil"></a></td>
                @if (userIsPower())
                  <td>
                    <a href="#" class="text-blue30w" title="Delete Project"
                      data-toggle="modal"
                      data-target="#modalDelete"
                      data-title="{{ $project->project_name }}"
                      data-action="{{ route('projects.destroy', routeParams(['id' => $project->id])) }}"
                      ><span class="glyphicon glyphicon-trash"></a>
                  </td>
                @endif
              @endif
            @endif
          @endif
        </tr>
        @if ($authorized)
          <tr>
            <td colspan="15" style="padding:0"> 
              <div id="fundingCollapse{{ $project->id }}" class="collapse" style="padding:.2em;" id="fundingCollapse{{ $project->id }}">
                @include('partials.project.funding', ['edit' => false])
              </div>
            </td>
          </tr>
        @endif
      @endforeach
      </tbody>
    </table>
    @if ($projects->count() == 0)
      <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i aria-hidden="true" class="ua-brand-x"></i>
        </button>
        There were no results. Please try again.
      </div>
    @endif
  </div>

  @include('partials.progress.request')
  @include('partials.question.create')
  @include('partials.confirm_delete')

@endsection

resources/views/project/questions.blade.php
@extends('layouts.app')

@section('breadcrumbs')
  @component('partials.breadcrumbs.project', ['project' => $project])
        <li class="active">Questions &amp; Answers</li>
  @endcomponent
@endsection

@section('title')
    Board Questions and Applicant Answers
@endsection

@section('content')
    <h3>{{ $project->project_name }}</h3>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Questions &amp; Answers</h3>
        </div>
        <div class="panel-body">
            @include('partials.question.index', ['questions' => $project->questions])
        </div>
    </div>
@endsection

resources/views/project/summary.blade.php
@extends('layouts.app')

@section('breadcrumbs')
  @component('partials.breadcrumbs.project_base', ['project' => $project])
        <li class="active">{{ $project->board_id or 'New Project' }}</li>
  @endcomponent
@endsection

@section('title')
    Project Summary
@endsection

@section('content')
    @if (session('success'))
        @component('partials.alert.base', ['type' => 'success'])
            <p>Your application is now closed and locked. You will receive an email confirmation shortly.</p>
            <p>Thank you for your application, and your interest in the {{ site()->name }}.</p>
        @endcomponent
    @endif
    <h3>{{ $project->project_name }}</h3>
    <h4>{{ $project->first_name }} {{ $project->last_name }}</h4>
    <p>
        Board Assigned ID: {{ $project->board_id }}
        <br>
        Project Created: {{ date('F j, Y g:i a', strtotime($project->created_at)) }}
    </p>
    @if(getActiveProjects()->where('id', $project->id)->count() > 0)
        <p><a href="{{ route('progress.create', routeParams(['project' => $project->id])) }}">Submit a Progress Report</a> | <a href="{{ route('pars.create', routeParams(['project' => $project->id])) }}">Submit a PAR</a></p>
    @endif

    @component('partials.project.main', ['summary' => true])
        @slot('project_information_left')
            <dl class="dl-horizontal">
                <dt>Project Name</dt>
                <dd>{{ $project->project_name }}</dd>
                <dt>Fiscal Year</dt>
                <dd>{{ $project->fiscal_year }}</dd>
            </dl>
        @endslot
        @slot('project_information_right')
        @endslot
        @slot('project_information_bottom')
            <h4>Funding</h4>
            @include('partials.project.funding', ['edit' => false])
        @endslot
        @slot('supporting_documents_top')
            <div class="row">
                <div class="col-md-6">
                    <h4>Project Plan</h4>
                    <ol>
                        <li>
                            @if (isset($project->fileDescriptionURL))
                                <a href="{{ $project->fileDescriptionURL }}">Original Project Description</a>
                            @else
                                No description attached
                            @endif
                        </li>
                        <li>
                            @if (isset($project->fileExtraURL))
                                <a href="{{ $project->fileExtraURL }}">Additional Information submitted with Project Application</a>
                            @else
                                No additional information attached
                            @endif
                        </li>
                        {{-- @if ($project->funding_status_id != 3) --}}
                            <li><a href="{{ route('projects.revisions', routeParams(['id' => $project->id])) }}">Revisions to Original Project Plan</a></li>
                        {{-- @endif --}}
                    </ol>
                    <h4>Project Budget</h4>
                    <ol>
                        <li>
                            @if (isset($project->fileBudgetURL))
                                <a href="{{ $project->fileBudgetURL }}">Original Project Budget Requested</a>
                            @else
                                No budget attached
                            @endif
                        </li>
                        <li>
                            @if (isset($project->currentYearBudgetURL))
                                <a href="{{ $project->currentYearBudgetURL }}">Current Year Approved Budget</a>
                            @else
                                No budget for current year
                            @endif
                        </li>
                        <li><a href="{{ route('projects.budgets', routeParams(['id' => $project->id])) }}">Budget History</a></li>
                    </ol>
                </div>
                <div class="col-md-6">
                    <h4>Other Documents</h4>
                    <ol>
                        <li><a href="{{ route('projects.notifications', routeParams(['id' => $project->id])) }}">Funding Notifications</a></li>
                        <li><a href="{{ route('progress.index', routeParams(['project' => $project->id])) }}">Progress Reports</a></li>
                        <li><a href="{{ route('pars.index', routeParams(['project' => $project->id])) }}">Program Alteration Requests (PARs)</a></li>
                        <li><a href="{{ route('projects.questions', routeParams(['id' => $project->id])) }}">Board Questions and Applicant Answers</a></li>
                        @if (Auth::check())
                            <li><a href="{{ route('projects.comments', routeParams(['id' => $project->id])) }}">Comments</a></li>
                        @endif
                    </ol>
                </div>
            </div>
            <p><a href="{{ route('projects.full', routeParams(['id' => $project->id])) }}">View Original Project Application</a></p>
        @endslot
        @include('partials.project.contact', ['confirm' => false])
    @endcomponent
@endsection

resources/views/project/view.blade.php
@extends('layouts.app')

@section('breadcrumbs')
  @component('partials.breadcrumbs.project_base', ['project' => $project])
      <li class="active">{{ $project->board_id or 'New Project' }}</li>
  @endcomponent
@endsection

@section('title')
  {{ $confirm ? 'Apply for Funding' : ($project->funding_status_id == 1 ? 'Application' : 'Project') }}
@endsection

@section('content')
  @if ($confirm)
    @component('partials.alert.base', ['type' => 'warning'])
      <p>You're almost finished! Your application has been saved and contains all the required information for final submission, <strong>but you must still submit the final version</strong>. To submit and lock your application, click the "Submit" button at the bottom of the page.</p>
    @endcomponent
  @elseif ($approve)
    @component('partials.alert.base', ['type' => 'warning'])
      @if ($project->signoff)
        <p>The project has already been approved.</p>
      @else
        <p>Clicking the "Approve" button will result in immediate and final approval. Please be sure you have fully reviewed the proposal below first. After approval, you and the applicant will receive a confirmation email.</p>
        <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data" action="{{ route('projects.approve', routeParams(['id' => $project->id])) }}">
          {{ method_field('PUT') }}
          {{ csrf_field() }}
          <p class="text-right">
            <button type="submit" class="btn btn-primary" value="0">Approve</button>
          </p>
        </form>
      @endif
    @endcomponent
  @else
    <h3>{{ $project->project_name }}</h3>
    <h4>{{ $project->first_name }} {{ $project->last_name }}</h4>
    <p>Board Assigned ID: {{ $project->board_id }}</p>
    <p><a href="{{ $project->url }}">Back to Summary</a></p>
  @endif

  @component('partials.project.main', ['summary' => false])
    @include('partials.project.contact')
    @slot('project_information_left')
      <dl class="dl-horizontal">
        <dt>Project Name</dt>
        <dd>{{ $project->project_name }}</dd>
        <dt>Fiscal Year</dt>
        <dd>{{ $project->fiscal_year }}</dd>
        <dt>Is this a new project?</dt>
        <dd>{{ formatBoolean($project->new_project) }}</dd>
        <dt>If no, has the {{ site()->name }} funded this request in the past?</dt>
        <dd>{{ formatBoolean($project->past_funding) }}</dd>
        <dt>Would a {{ site()->name }} allocation be the sole funding for this initiative?</dt>
        <dd>{{ formatBoolean($project->sole_funding) }}</dd>
      </dl>
    @endslot
    @slot('project_information_right')
      <dl class="dl-horizontal">
        <dt>Duration</dt>
        <dd>{{ $project->duration }} year(s)</dd>
        <dt>Multi-year justification</dt>
        <dd>{{ $project->justification }}</dd>
        <dt>Total Project Funding Requested</dt>
        <dd>${{ number_format($project->totalFunding->requested_amount) }}</dd>
        @foreach ($project->allFundings as $funding)
          <dt>Requested Funding - Year {{ $funding->year }}</dt>
          <dd>${{ number_format($funding->requested_amount) }}</dd>
        @endforeach
      </dl>
    @endslot
    @slot('project_information_bottom')
      @if ($project->undergraduateInitiatives->count() > 0)
        <p>Undergraduate initiatives identified in the annual Survey Results this project would support:</p>
        <ol>
          @foreach ($project->undergraduateInitiatives->unique() as $initiative)
            <li>{{ $initiative->name }}</li>
          @endforeach
        </ol>
      @endif

      @if ($project->graduateInitiatives->count() > 0)
        <p>Graduate initiatives identified in the annual Survey Results this project would support:</p>
        <ol>
          @foreach ($project->graduateInitiatives->unique() as $initiative)
            <li>{{ $initiative->name }}</li>
          @endforeach
        </ol>
      @endif
    @endslot
    @slot('supporting_documents_top')
    @endslot
    @slot('supporting_documents_1')
      @if (isset($project->fileBudgetURL))
        <p><a href="{{ $project->fileBudgetURL }}">Budget</a></p>
      @else
        <p>No budget attached</p>
      @endif
    @endslot
    @slot('supporting_documents_2')
      @if (isset($project->fileDescriptionURL))
        <p><a href="{{ $project->fileDescriptionURL }}">Description</a></p>
      @else
        <p>No description attached</p>
      @endif
    @endslot
    @slot('supporting_documents_3')
      @if (isset($project->fileExtraURL))
        <p><a href="{{ $project->fileExtraURL }}">Additional Information</a></p>
      @else
        <p>No additional information addatched</p>
      @endif
    @endslot
    @slot('terms')
      <p><strong>I [{{ $project->agree_terms ? 'agree' : 'do not agree'}}] to the terms and conditions and wish to have my application considered for funding.</strong></p>
    @endslot
  @endcomponent
  @if ($confirm)
    <p class="text-right">
      <a href="{{ route('projects.edit', routeParams(['id' => $project->id])) }}" class="btn btn-default" name="save_draft" value="1">Edit</a>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalConfirmSave">Submit Final Version</button>
    </p>

    <div class="modal fade" id="modalConfirmSave">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i aria-hidden="true" class="ua-brand-x"></i></button>
            <h4 class="modal-title">Submit Application?</h4>
          </div>
          <div class="modal-body">
            <p>You are about to <strong>SUBMIT AND LOCK</strong> your final application. If you continue with this process, you will not be able to return to make future edits. Are you sure you want to continue?</p>
          </div>
          <div class="modal-footer">
            <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data" action="{{ route('projects.save', routeParams(['id' => $project->id])) }}">
              {{ method_field('PUT') }}
              {{ csrf_field() }}
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
              <button type="submit" class="btn btn-primary" value="0">Yes</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  @endif
@endsection