routes/web.php
<?php

use App\Site;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// sites
Route::group(['prefix' => 'sites', 'as' => 'sites.'], function () {
  Route::post('{id}/files/save', 'SiteController@saveFiles')->name('files.save');
  Route::delete('{id}/files/{file_id}/delete', 'SiteController@deleteFile')->name('files.destroy');
  Route::post('{id}/departments/save', 'SiteController@saveDepartment')->name('departments.save');
  Route::delete('{id}/departments/{dept_id}/delete', 'SiteController@deleteDepartment')->name('departments.destroy');
  Route::post('{id}/initiatives/save', 'SiteController@saveInitiative')->name('initiatives.save');
  Route::put('{id}/initiatives/{init_id}/update', 'SiteController@updateInitiative')->name('initiatives.update');
  Route::delete('{id}/initiatives/{init_id}/delete', 'SiteController@deleteInitiative')->name('initiatives.destroy');
});
Route::resource('sites', 'SiteController');

// site specific routes
Route::group(['prefix' => '{site}'], function () {
  Route::get('/', 'SiteController@show')->name('index');
  Route::get('contact', 'SiteController@contact')->name('contact');
  Route::post('contact', 'SiteController@contactSend')->name('contact.send');
  Route::get('admin', 'SiteController@admin')->name('admin');

  // pages (editing)
  Route::put('pages/order', 'PageController@updateOrder')->name('pages.order');
  Route::resource('pages', 'PageController');

  // project sets
  Route::group(['prefix' => 'project-sets', 'as' => 'project-sets.'], function() {
    Route::get('{id}/set', 'ProjectSetController@setSession')->name('set');
  });
  Route::resource('project-sets', 'ProjectSetController');

  // questions and answers
  Route::post('{id}/extend', 'QuestionController@questionExtension')->name('questions.questionExtension');

  // Route::get('{id}/extend/done','QuestionController@questionExtensionDone');
  Route::resource('questions', 'QuestionController');

  Route::resource('answers', 'AnswerController');

  // users
  Route::resource('users', 'UserController');
  Route::put('users/site/update', 'UserController@updateSite')->name('users.site.update');
  Route::get('directory', 'UserController@directory')->name('users.directory');
  Route::group(['prefix' => 'board/apply'], function() {
    Route::get('/', 'UserController@apply')->name('users.apply');
    Route::post('/', 'UserController@applyStore')->name('users.apply.store');
    Route::get('index', 'UserController@applyIndex')->name('users.apply.index');
    Route::get('{id}/view', 'UserController@applyView')->name('users.apply.view');
    Route::get('{id}/confirm', 'UserController@confirm')->name('users.apply.confirm');
    Route::get('{id}/edit', 'UserController@applyEdit')->name('users.apply.edit');
    Route::put('{id}', 'UserController@applyUpdate')->name('users.apply.update');
    Route::put('{id}/save', 'UserController@applySave')->name('users.apply.save');
    Route::put('{id}/accept', 'UserController@applyAccept')->name('users.apply.accept');
    Route::delete('{id}/destroy', 'UserController@applyDestroy')->name('users.apply.destroy');
  });

  Route::group(['prefix' => '{project_set}'], function() {
    // custom project routes
    Route::group(['prefix' => 'projects', 'as' => 'projects.'], function () {
      Route::get('start', 'ProjectController@createStart')->name('start');
      Route::put('save', 'ProjectController@save')->name('save');
      Route::put('approve', 'ProjectController@approve')->name('approve');
      Route::get('review', 'ProjectController@review')->name('review');
      Route::get('admin', 'ProjectController@admin')->name('admin.index');
      Route::get('{id}/admin', 'ProjectController@adminEdit')->name('admin.edit');
      Route::get('{id}/confirm', 'ProjectController@confirm')->name('apply.confirm');
      Route::get('{id}/approve', 'ProjectController@showApprove')->name('apply.approve');
      Route::get('{id}/full', 'ProjectController@full')->name('full');
      Route::post('{id}/remind', 'ProjectController@remind')->name('remind');
      Route::get('{id}/files', 'ProjectController@files')->name('files');
      Route::post('{id}/files/save', 'ProjectController@saveFile')->name('files.save');
      Route::delete('files/{id}/delete', 'ProjectController@deleteFile')->name('files.destroy');
      Route::put('files/{id}/move', 'ProjectController@moveFile')->name('files.move');
      Route::get('{id}/revisions', 'ProjectController@revisions')->name('revisions');
      Route::get('{id}/budgets', 'ProjectController@budgets')->name('budgets');
      Route::get('{id}/notifications', 'ProjectController@notifications')->name('notifications');
      Route::get('{id}/questions', 'ProjectController@questions')->name('questions');
      Route::get('{id}/comments', 'ProjectController@comments')->name('comments');
      Route::post('{id}/comments/save', 'ProjectController@saveComment')->name('comments.save');
    });
    // project resource routes
    Route::resource('projects', 'ProjectController');

    // progress reports
    Route::group(['prefix' => 'progress', 'as' => 'progress.'], function() {
      Route::get('start', 'ProgressReportController@createStart')->name('start');
      Route::get('{id}/review', 'ProgressReportController@review')->name('review');
      Route::get('{id}/admin', 'ProgressReportController@adminEdit')->name('admin');
      Route::post('send', 'ProgressReportController@send')->name('send');
      Route::put('{id}/move', 'ProgressReportController@move')->name('move');
    });
    Route::resource('progress', 'ProgressReportController');

    // pars
    Route::group(['prefix' => 'pars', 'as' => 'pars.'], function() {
      Route::get('start', 'ParController@createStart')->name('start');
      Route::get('admin', 'ParController@admin')->name('admin.index');
      Route::get('{id}/review', 'ParController@review')->name('review');
      Route::get('{id}/advice', 'ParController@advice')->name('advice');
      Route::put('{id}/advice/update', 'ParController@updateAdvice')->name('advice.update');
      Route::get('{id}/advice/review', 'ParController@reviewAdvice')->name('advice.review');
      Route::get('{id}/vp', 'ParController@vp')->name('vp');
      Route::put('{id}/vp/update', 'ParController@updateVp')->name('vp.update');
      Route::get('{id}/vp/review', 'ParController@reviewVp')->name('vp.review');
      Route::get('{id}/approve', 'ParController@approve')->name('approve');
      Route::get('{id}/admin/edit', 'ParController@adminEdit')->name('admin.edit');
    });
    Route::resource('pars', 'ParController');
  });

  // login
  Route::get('login', 'UserController@login')->name('login');

  // handle redirects from webauth
  Route::get('webauth/redirect', ['as' => 'guest.login.redirect', 'uses' => 'WebauthController@redirect']);

  // this goes last to not catch anything important
  Route::get('/{any}', 'PageController@showBySlug')->where('any', '.*');
});

app/ProjectSet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProjectSet extends Model
{
    // get the site this project set belongs to
    public function site()
    {
        return $this->belongsTo('App\Site');
    }

    // get the projects for this set
    public function projects()
    {
        return $this->hasMany('App\Project');
    }
    
    // get the files for this project set
    public function files()
    {
        return $this->morphMany('App\File', 'fileable');
    }

    // url to projects index
    public function getProjectsURLAttribute()
    {
        return route('projects.index', ['site' => $this->site->slug, 'project_set' => $this->slug]);
    }

    public function getAppDeadlineTimeAttribute()
    {
        return date('g:i a', strtotime($this->application_deadline));
    }

    public function getAppDeadlineDateAttribute()
    {
        return formatDeadline($this->application_deadline);
    }

    public function getProgressDeadlineDateAttribute()
    {
        return formatDeadline($this->progress_deadline);
    }
    
    // full url for budget template
    public function getBudgetTemplateUrlAttribute()
    {
      return getFileUrl($this->files, 1);
    }

    public function getBudgetTemplateTitleAttribute()
    {
      return getFileTitle($this->files, 1);
    }
}

app/Site.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Site extends Model
{
    // get the pages that belong to this site
    public function pages()
    {
        return $this->hasMany('App\Page');
    }

    // get the Project Sets that belong to this site
    public function projectSets()
    {
      return $this->hasMany('App\ProjectSet');
    }

    // get the departments associated with this site
    public function departments()
    {
      return $this->hasMany('App\Department')->orderBy('name');
    }

    // get the initiatives associated with this site
    public function initiatives()
    {
      return $this->hasMany('App\Initiative');
    }

    // get the contact for this site
    public function contact()
    {
      return $this->belongsTo('App\User', 'contact_id');
    }

    // get the users that are associated with this site
    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    // get the files for this site
    public function files()
    {
        return $this->morphMany('App\File', 'fileable');
    }

    // get uploads for the site
    public function getUploadsAttribute()
    {
        return $this->files->where('file_type_id', 8);
    }

    // get the url for the site
    public function getUrlAttribute()
    {
      return route('index', ['site' => $this->slug]);
    }

    // get the governing doc url
    public function getGoverningDocUrlAttribute()
    {
      return getFileUrl($this->files, 7);
    }

    public function getGoverningDocTitleAttribute()
    {
      return getFileTitle($this->files, 7);
    }

    // get the governing doc url
    public function getBoardRequirementsUrlAttribute()
    {
      return getFileUrl($this->files, 3);
    }

    // get the homepage
    public function getHomeAttribute()
    {
      return $this->pages()->where('default', 1)->first();
    }

    public function getBoardAppDeadlineTimeAttribute()
    {
        return date('g:i a', strtotime($this->board_application_deadline));
    }

    public function getBoardAppDeadlineDateAttribute()
    {
        return formatDeadline($this->board_application_deadline);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'student_id',
        'phone',
        'email',
        'address',
        'city',
        'state',
        'zip',
        'club_org_1',
        'club_org_2',
        'club_org_3',
        'club_org_4',
        'user_title_id',
        'text',
        'user_standing_id',
        'user_type_id',
        'user_status_id',
        'responsibilities',
        'netid',
        'role_id',
        'start_year',
        'fiscal_year',
        'directory',
        'par_contact',
        'question_contact',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // get the role this user has
    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    // get the status of this user
    public function status()
    {
        return $this->belongsTo('App\UserStatus', 'user_status_id');
    }

    // get the standing for this user
    public function standing()
    {
        return $this->belongsTo('App\UserStanding', 'user_standing_id');
    }

    // get the title of this user
    public function title()
    {
        return $this->belongsTo('App\UserTitle', 'user_title_id');
    }

    // get the type of this user
    public function type()
    {
        return $this->belongsTo('App\UserType', 'user_type_id');
    }

    // get the applications belonging to this user
    public function applications()
    {
        return $this->hasMany('App\UserApplication');
    }

    // get the sites associated with this user
    public function sites()
    {
        return $this->belongsToMany('App\Site');
    }

    // check if the user is an admin
    public function isAdmin()
    {
        return $this->role->id == 4;
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    // clean up relations before deleting
    public function delete()
    {
        $this->applications()->delete();
        Parent::delete();
    }
}

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('breadcrumbs')
  @component('partials.breadcrumbs.base')
    <li class="active">Board Room</li>
  @endcomponent
@endsection

@section('title')
  Board Room
@endsection

@section('content')

  @if (null !== session('applicants'))
    @component('partials.alert.base', ['type' => session('applicants') > 0 ? 'success' : 'warning'])
      @if (session('applicants') > 0)
        <h4>Success</h4>
        <p>Your request has been sent to <strong>{{ session('applicants') }}</strong> applicants.</p>
      @else
        <h4>Warning</h4>
        <p>Your progress report request could not be sent because no applications meet the necessary criteria.</p>
      @endif
    @endcomponent
  @endif

  <div class="row">
    @if (site()->projectSets->count() > 0)
      <div class="col-md-6">
        <h2>Project Tools</h2>
        <h4>General Review &amp; Discussion</h4>
        <ul>
          <li><a href="{{ route('projects.review', baseRouteParams()) }}">Review Applications</a></li>
          <li><a href="{{ route('pars.admin.index', baseRouteParams()) }}">Review PARs</a></li>
        </ul>
        @if(userIsChair())
          <h4>Administrative Tasks</h4>
          <ul>
            <li><a href="{{ route('projects.admin.index', baseRouteParams()) }}">Edit Projects</a></li>
            @if(userIsAdmin())
              <li>
                <a href="#" title="Request Progress Report"
                    data-toggle="modal"
                    data-target="#modalRequestReport">
                    Semi-Annual Progress Report Request
                </a>
              </li>
              @if(userIsPower())
                <li><a href="{{ route('projects.start', baseRouteParams()) }}">View Application</a></li>
              @endif
            @endif
          </ul>
        @endif
      </div>
    @endif
    <div class="col-md-6">
      <h2>Board Membership</h2>
      <ul>
        <li><a href="{{ route('users.apply.index', ['site' => site()->slug]) }}">Review Applications</a></li>
        @if (userIsPower())
          <li><a href="{{ route('users.create', ['site' => site()->slug]) }}">Add a Board Member</a></li>
          <li><a href="{{ route('users.index', ['site' => site()->slug]) }}">Edit Board Members</a></li>
          <li><a href="{{ route('users.apply', ['site' => site()->slug]) }}">View Application</a></li>
        @endif
      </ul>
      @if (userIsPower())
        <h2>Site Maintenance</h2>
        <ul>  
          @if (site()->projectSets->count() > 0)
            <li><a href="{{ route('project-sets.edit', ['slug' => site()->slug, 'project_set' => projectSet()->id]) }}">Update Deadlines &amp; Templates</a></li>
          @endif
          <li><a href="{{ route('sites.edit', ['id' => site()->id])}}">Update Site Settings</a></li>
          <li><a href="{{ route('pages.index', ['site' => site()->slug])}}">Manage Content</a></li>
        </ul>
      @endif
    </div>
  </div>

  @if (site()->projectSets->count() > 0)
    @include('partials.progress.request')
  @endif

@endsection

resources/views/admin/project-set.blade.php
@extends('layouts.app')

@section('breadcrumbs')
  @component('partials.breadcrumbs.default')
    <li class="active">Deadlines &amp; Templates</li>
  @endcomponent
@endsection

@section('title')
  Update Deadlines
@endsection

@section('content')
  <p>Use the forms below to set deadlines for the various tasks associated with board membership and funding applications. Deadlines that do not support exact cutoff times are based on end-of-day occurring at midnight the following day. For instance, setting a deadline of January 15, {{ date('Y') }} will allow the task to be performed through the end of that day; until 12:00:00 a.m. on January 16, {{ date('Y') }}.</p>
  <p>For deadlines driven by a "number of days" setting, the deadline will pass when the exact number of days have elapsed since the time the question was submitted. For example, if the deadline is set to 3 days and a question is submitted on a Monday at 9:00 a.m., the question will 'expire' on Thursday at 9:00 a.m. of that same week. Changes to question deadlines are not retroactive, i.e., questions already sent under one deadline setting will not be impacted by future deadline changes.</p>
  <form role="form" method="POST" enctype="multipart/form-data" action="{{ route('project-sets.update', [site()->slug, 'id' => $project_set->id]) }}">
    {{ method_field('PUT') }}
    {{ csrf_field() }}
    <div class="panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title">Deadlines, Cutoffs &amp; Templates</h3>
      </div>
      <div class="panel-body">
        <h4>Funding Application Submission Deadline</h4>
        <p>This deadline controls the availability of the funding application form and the associated deadline date that appears in text on the application form, the "<a href="{{ route('projects.start', baseRouteParams()) }}">Apply for Funding</a>" page, the "<a href="{{ site()->pages->first()->url }}">{{ site()->pages->first()->title }}</a>" page, and all dates in system-generated email correspondence. <strong>Please be aware that the application will not be live until the Open Date. It will then go offline after the close date.</strong></p>
        @component('partials.form.field', ['inline' => false, 'name' => 'application_open', 'label' => 'Open Date'])
            <div class="input-group date datetimepicker" id="applicationOpen">
                <input name="application_open" type="text" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        @endcomponent
        @component('partials.form.field', ['inline' => false, 'name' => 'application_deadline', 'label' => 'Close Date'])
            <div class="input-group date datetimepicker" id="applicationDeadline">
                <input name="application_deadline" type="text" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        @endcomponent
        <hr>
        <h4>Board Member Application Submission Deadline</h4>
        <p>This deadline controls the availability of the board member application form and the associated deadline date that appears in text on the application form and the "Apply for membership" link on the "Board Information" page. <strong>Please be aware that the application will not be live until the Open Date. It will then go offline after the close date.</strong></p>
        @component('partials.form.field', ['inline' => false, 'name' => 'board_application_open', 'label' => 'Open Date'])
            <div class="input-group date datetimepicker" id="boardApplicationOpen">
                <input name="board_application_open" type="text" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        @endcomponent
        @component('partials.form.field', ['inline' => false, 'name' => 'board_application_deadline', 'label' => 'Close Date'])
            <div class="input-group date datetimepicker" id="boardApplicationDeadline">
                <input name="board_application_deadline" type="text" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        @endcomponent
        <hr>
        <h4>Semi-Annual Progress Report Due Date</h4>
        <p>This deadline will appear in emails generated by using the "Semi-Annual Progress Report Request" tool, accessible from the <a href="{{ route('admin', ['site' => site()->slug]) }}">Board Room</a> main page. <strong>These deadlines ARE NOT programmed to be 'enforced' by the Board Room system.</strong> An applicant will still have the ability to submit a progress report after the due date, but the date/time of submission will be noted in the progress report. Changes to progress report deadlines are not retroactive, i.e., requests already sent under one deadline setting will <strong>NOT</strong> be impacted by future deadline changes.</p>
        <div class="form-group">
            <div class="input-group date datetimepicker" id="progressDeadline">
                <input name="progress_deadline" type="text" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        <hr>
        <h4>Days to Respond to Questions From The Board</h4>
        <p>This deadline will appear in the email generated when a board member submits a question to an applicant about their funding application. <strong>These deadlines ARE programmed to be 'enforced' by the Board Room system.</strong> An applicant will receive an 'expired notice' on the web page if they attempt to respond to a question after the deadline has passed. Changes to question deadlines are not retroactive, i.e., questions already sent under one deadline setting will <strong>NOT</strong> be impacted by future deadline changes.</p>
        @include('partials.form.text', ['inline' => false, 'type' => 'text', 'name' => 'question_deadline', 'object' => $project_set])
        <hr>
        <h4>Fiscal Cutoff Month</h4>
        <p>This is used to determine the project start year based on the fiscal cutoff month and whether a year gets added or subtracted. If 'Add Year After Cutoff' is checked and the current month is the same as or after to the fiscal cutoff, the start year will be advanced to the next year. Otherwise, if 'Add Year After Cutoff' is not checked and the current month is before the cutoff month, the start year will be stepped back to the previous year.</p>
        <div class="form-group">
          <div class="input-group date datetimepicker" id="fiscalCutoff">
              <input name="fiscal_cutoff_month" type="text" class="form-control" />
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
          </div>
        </div>
        @include('partials.form.checkbox', ['name' => 'fiscal_cutoff_add', 'value' => 1, 'label' => 'Add Year After Cutoff?', 'object' => $project_set])
        <h4>Budget Template</h4>
        <p><a href="{{ projectSet()->budget_template_url }}">{{ projectSet()->budget_template_title }}</a></p>
        <input type="file" name="budget_template">
      </div>
      <div class="panel-footer text-right">
        <a href="{{ route('admin', ['site' => site()->slug]) }}" class="btn btn-default">Cancel</a>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
@endsection

@section('scripts')
  <script type="text/javascript">
    $('#fiscalCutoff').data('DateTimePicker').options({
      format: 'MMMM',
      viewMode: 'months',
    });

    window.setDatePickerDate('{{ null !== old('application_open') ? old('application_open') : $project_set->application_open }}', '#applicationOpen');
    window.setDatePickerDate('{{ null !== old('application_deadline') ? old('application_deadline') : $project_set->application_deadline }}', '#applicationDeadline');
    window.setDatePickerDate('{{ null !== old('board_application_deadline') ? old('board_application_deadline') : $project_set->site->board_application_deadline }}', '#boardApplicationDeadline');
    window.setDatePickerDate('{{ null !== old('board_application_open') ? old('board_application_open') : $project_set->site->board_application_open }}', '#boardApplicationOpen');
    window.setDatePickerDate('{{ null !== old('progress_deadline') ? old('progress_deadline') : $project_set->progress_deadline }}', '#progressDeadline');
    window.setDatePickerDate('{{ date('Y') . '-' . (null !== old('fiscal_cutoff_month') ? date_parse(old('fiscal_cutoff_month'))['month'] : $project_set->fiscal_cutoff_month) . '-01 00:00:00' }}', '#fiscalCutoff');
  </script>
@endsection

resources/views/admin/site.blade.php
@extends('layouts.app')

@section('breadcrumbs')
  @component('partials.breadcrumbs.default')
    <li class="active">Site Settings</li>
  @endcomponent
@endsection

@section('title')
  Site Settings
@endsection

@section('content')
    <p>The form below allows you to edit various settings of the {{ site()->name }} website, such as name, contact information and budget template.</p>
    <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data" action="{{ route('sites.update', ['id' => site()->id]) }}">
        {{ method_field('PUT') }}
        {{ csrf_field() }}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Site Settings</h3>
            </div>
            <div class="panel-body">
                @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'name', 'label' => 'Site Name', 'object' => site()])
                @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'abbreviation', 'label' => 'Abbreviation', 'object' => site()])
                @component('partials.form.field', ['inline' => true, 'name' => 'contact_id', 'label' => 'Site Contact'])
                    <select name="contact_id" class="form-control">
                        <option value="">Select...</option>
                        @foreach ($users as $user)
                            <option value="{{ $user->id }}"{{ null !== old('contact_id') ? (old('contact_id') == $user->id ? ' selected' : '') : ((null !== site()->contact && site()->contact->id == $user->id) ? ' selected' : '') }}>{{ $user->full_name }} ({{ $user->netid }})</option>
                        @endforeach
                    </select>
                @endcomponent
                @component('partials.form.field', ['inline' => true, 'name' => 'governing_doc', 'label' => 'Governing Document'])
                    <p><a href="{{ site()->governing_doc_url }}">{{ site()->governing_doc_title }}</a></p>
                    <input type="file" name="governing_doc">
                @endcomponent
                @component('partials.form.field', ['inline' => true, 'name' => 'info', 'label' => 'Funding Application Instructions'])
                    <textarea name="funding_app_instructions" class="summernote">
                        {!! null !== old('funding_app_instructions') ? old('funding_app_instructions') : (null !== site()->funding_app_instructions ? site()->funding_app_instructions : '') !!}
                    </textarea>
                @endcomponent
                @component('partials.form.field', ['inline' => true, 'name' => 'info', 'label' => 'Board Application Instructions'])
                    <textarea name="board_app_instructions" class="summernote">
                        {!! null !== old('board_app_instructions') ? old('board_app_instructions') : (null !== site()->board_app_instructions ? site()->board_app_instructions : '') !!}
                    </textarea>
                @endcomponent
            </div>
            <div class="panel-footer text-right">
                <a href="{{ route('admin', ['site' => site()->slug]) }}" class="btn btn-default">Cancel</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection