routes/web.php
<?php

use App\Site;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// sites
Route::group(['prefix' => 'sites', 'as' => 'sites.'], function () {
  Route::post('{id}/files/save', 'SiteController@saveFiles')->name('files.save');
  Route::delete('{id}/files/{file_id}/delete', 'SiteController@deleteFile')->name('files.destroy');
  Route::post('{id}/departments/save', 'SiteController@saveDepartment')->name('departments.save');
  Route::delete('{id}/departments/{dept_id}/delete', 'SiteController@deleteDepartment')->name('departments.destroy');
  Route::post('{id}/initiatives/save', 'SiteController@saveInitiative')->name('initiatives.save');
  Route::put('{id}/initiatives/{init_id}/update', 'SiteController@updateInitiative')->name('initiatives.update');
  Route::delete('{id}/initiatives/{init_id}/delete', 'SiteController@deleteInitiative')->name('initiatives.destroy');
});
Route::resource('sites', 'SiteController');

// site specific routes
Route::group(['prefix' => '{site}'], function () {
  Route::get('/', 'SiteController@show')->name('index');
  Route::get('contact', 'SiteController@contact')->name('contact');
  Route::post('contact', 'SiteController@contactSend')->name('contact.send');
  Route::get('admin', 'SiteController@admin')->name('admin');

  // pages (editing)
  Route::put('pages/order', 'PageController@updateOrder')->name('pages.order');
  Route::resource('pages', 'PageController');

  // project sets
  Route::group(['prefix' => 'project-sets', 'as' => 'project-sets.'], function() {
    Route::get('{id}/set', 'ProjectSetController@setSession')->name('set');
  });
  Route::resource('project-sets', 'ProjectSetController');

  // questions and answers
  Route::post('{id}/extend', 'QuestionController@questionExtension')->name('questions.questionExtension');

  // Route::get('{id}/extend/done','QuestionController@questionExtensionDone');
  Route::resource('questions', 'QuestionController');

  Route::resource('answers', 'AnswerController');

  // users
  Route::resource('users', 'UserController');
  Route::put('users/site/update', 'UserController@updateSite')->name('users.site.update');
  Route::get('directory', 'UserController@directory')->name('users.directory');
  Route::group(['prefix' => 'board/apply'], function() {
    Route::get('/', 'UserController@apply')->name('users.apply');
    Route::post('/', 'UserController@applyStore')->name('users.apply.store');
    Route::get('index', 'UserController@applyIndex')->name('users.apply.index');
    Route::get('{id}/view', 'UserController@applyView')->name('users.apply.view');
    Route::get('{id}/confirm', 'UserController@confirm')->name('users.apply.confirm');
    Route::get('{id}/edit', 'UserController@applyEdit')->name('users.apply.edit');
    Route::put('{id}', 'UserController@applyUpdate')->name('users.apply.update');
    Route::put('{id}/save', 'UserController@applySave')->name('users.apply.save');
    Route::put('{id}/accept', 'UserController@applyAccept')->name('users.apply.accept');
    Route::delete('{id}/destroy', 'UserController@applyDestroy')->name('users.apply.destroy');
  });

  Route::group(['prefix' => '{project_set}'], function() {
    // custom project routes
    Route::group(['prefix' => 'projects', 'as' => 'projects.'], function () {
      Route::get('start', 'ProjectController@createStart')->name('start');
      Route::put('save', 'ProjectController@save')->name('save');
      Route::put('approve', 'ProjectController@approve')->name('approve');
      Route::get('review', 'ProjectController@review')->name('review');
      Route::get('admin', 'ProjectController@admin')->name('admin.index');
      Route::get('{id}/admin', 'ProjectController@adminEdit')->name('admin.edit');
      Route::get('{id}/confirm', 'ProjectController@confirm')->name('apply.confirm');
      Route::get('{id}/approve', 'ProjectController@showApprove')->name('apply.approve');
      Route::get('{id}/full', 'ProjectController@full')->name('full');
      Route::post('{id}/remind', 'ProjectController@remind')->name('remind');
      Route::get('{id}/files', 'ProjectController@files')->name('files');
      Route::post('{id}/files/save', 'ProjectController@saveFile')->name('files.save');
      Route::delete('files/{id}/delete', 'ProjectController@deleteFile')->name('files.destroy');
      Route::put('files/{id}/move', 'ProjectController@moveFile')->name('files.move');
      Route::get('{id}/revisions', 'ProjectController@revisions')->name('revisions');
      Route::get('{id}/budgets', 'ProjectController@budgets')->name('budgets');
      Route::get('{id}/notifications', 'ProjectController@notifications')->name('notifications');
      Route::get('{id}/questions', 'ProjectController@questions')->name('questions');
      Route::get('{id}/comments', 'ProjectController@comments')->name('comments');
      Route::post('{id}/comments/save', 'ProjectController@saveComment')->name('comments.save');
    });
    // project resource routes
    Route::resource('projects', 'ProjectController');

    // progress reports
    Route::group(['prefix' => 'progress', 'as' => 'progress.'], function() {
      Route::get('start', 'ProgressReportController@createStart')->name('start');
      Route::get('{id}/review', 'ProgressReportController@review')->name('review');
      Route::get('{id}/admin', 'ProgressReportController@adminEdit')->name('admin');
      Route::post('send', 'ProgressReportController@send')->name('send');
      Route::put('{id}/move', 'ProgressReportController@move')->name('move');
    });
    Route::resource('progress', 'ProgressReportController');

    // pars
    Route::group(['prefix' => 'pars', 'as' => 'pars.'], function() {
      Route::get('start', 'ParController@createStart')->name('start');
      Route::get('admin', 'ParController@admin')->name('admin.index');
      Route::get('{id}/review', 'ParController@review')->name('review');
      Route::get('{id}/advice', 'ParController@advice')->name('advice');
      Route::put('{id}/advice/update', 'ParController@updateAdvice')->name('advice.update');
      Route::get('{id}/advice/review', 'ParController@reviewAdvice')->name('advice.review');
      Route::get('{id}/vp', 'ParController@vp')->name('vp');
      Route::put('{id}/vp/update', 'ParController@updateVp')->name('vp.update');
      Route::get('{id}/vp/review', 'ParController@reviewVp')->name('vp.review');
      Route::get('{id}/approve', 'ParController@approve')->name('approve');
      Route::get('{id}/admin/edit', 'ParController@adminEdit')->name('admin.edit');
    });
    Route::resource('pars', 'ParController');
  });

  // login
  Route::get('login', 'UserController@login')->name('login');

  // handle redirects from webauth
  Route::get('webauth/redirect', ['as' => 'guest.login.redirect', 'uses' => 'WebauthController@redirect']);

  // this goes last to not catch anything important
  Route::get('/{any}', 'PageController@showBySlug')->where('any', '.*');
});

app/Par.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Par extends Model
{
    // get the project this PAR belongs to
    public function project()
    {
        return $this->belongsTo('App\Project');
    }

    // get the files for this PAR
    public function files()
    {
        return $this->morphMany('App\File', 'fileable');
    }

    // get the questions for this PAR
    public function questions()
    {
        return $this->morphMany('App\Question', 'questionable');
    }

    // full url for supporting file
    public function getFileSupportURLAttribute()
    {
        return getFileUrl($this->files, 2);
    }

    // full url for advice file
    public function getFileAdviceURLAttribute()
    {
        return getFileUrl($this->files, 6);
    }

    // if there is no board id in the db, auto generate one. use 'T' to indicate temporary
    public function getBoardIdAttribute($value)
    {
        return isset($value) ? $value : site()->abbreviation . '-T' . $this->id;
    }

    // clean up relationships on delete
    public function delete()
    {
        deleteItems($this->files);
        deleteItems($this->questions);
        Parent::delete();
    }
}

resources/views/par/advice.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    @component('partials.breadcrumbs.par')
        <li class="active">Advice</li>
    @endcomponent
@endsection

@section('title')
  Submit Advice
@endsection

@section('content')
    <h3>{{ $par->project->project_name }}</h3>
    <p>Use the form below to submit an Advice for PAR {{ $par->board_id }}.</p>
    <p><strong>NOTE:</strong> For best results, please <strong>enter plain text</strong>. Pasting preformatted Word content may yield unpredictable results. If you already have formatted content in Word, try saving the Word document as plain text or copying the content into a plain text editor such as Notepad or TextEdit. Then copy/paste the plain text content into this form.</p>
    <p><strong>ALSO NOTE:</strong> this Advice will be part of the original proposal's permanent record and <strong>will be viewable by the general public.</strong></p>

    <form role="form" method="POST" enctype="multipart/form-data" action="{{ route('pars.advice.update', routeParams(['id' => $par->id])) }}">
    {{ method_field('PUT') }}
    {{ csrf_field() }}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Advice Information</h3>
            </div>
            @component('partials.par.main', ['mode' => $mode])
                @include('partials.par.advice')
            @endcomponent
            <div class="panel-footer text-right">
                <input type="hidden" name="par_id" value="{{ $par->id }}">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>

@endsection

resources/views/par/create.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    @if ($mode == 4)
        @component('partials.breadcrumbs.par')
            <li class="active">{{ $par->board_id }}</li>
        @endcomponent
    @else
        @component('partials.breadcrumbs.base')
            <li><a href="{{ route('pars.start', baseRouteParams()) }}">PARs</a></li>
            <li class="active">{{ $project->board_id or $project->project_name }}</li>
        @endcomponent
    @endif
@endsection

@section('title')
    @if ($mode == 4)
        Edit PAR
    @else
        Submit PARs
    @endif
@endsection

@section('content')
    <h3>{{ $project->project_name }}</h3>
    @if (!isset($par) && $project->netid != $netid && $project->director_netid != $netid)    
        @include('partials.alert.contact-mismatch', ['title' => 'PAR'])
    @else
        @if (isset($par))
            <form role="form" method="POST" enctype="multipart/form-data" action="{{ route('pars.update', routeParams(['id' => $par->id])) }}">
            {{ method_field('PUT') }}
        @else
            <p>
                <strong>Welcome, {{ $project->director_netid == $netid ? $project->director_first_name : $project->first_name }}.</strong><br>
                Use the form below to complete your PAR for the {{ $project->project_name }} initiative.
            </p>
            <p>
                <strong>NOTE:</strong> For best results, please <strong>enter plain text</strong>. Pasting preformatted Word content may yield unpredictable results.
                If you already have formatted content in Word, try saving the Word document as plain text or copying the content into a plain text editor such as Notepad or TextEdit. Then copy/paste the plain text content into this form.
                ALSO NOTE, PARs are part of this application's permanent record and <strong>will be viewable by the general public</strong>. 
            </p>

            <form role="form" method="POST" enctype="multipart/form-data" action="{{ route('pars.store', baseRouteParams()) }}">
        @endif
            {{ csrf_field() }}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">PAR Information</h3>
                </div>
                @component('partials.par.main', ['mode' => $mode])
                    @slot('introduction')
                        @if ($mode == 4)
                            @include('partials.form.text', ['inline' => false, 'type' => 'text', 'name' => 'board_id', 'label' => 'Override Board ID', 'object' => isset($par) ? $par : null])
                        @endif
                    @endslot
                    @slot('changes')
                        @include('partials.form.textarea', ['name' => 'changes', 'label' => '', 'object' => isset($par) ? $par : null])
                    @endslot
                    @slot('document')
                        @if (isset($par->fileSupportURL))
                            <p><a href="{{ $par->fileSupportURL }}">Supporting Document</a></p>
                        @endif
                        @component('partials.form.field_base', ['name' => 'file_support', 'label' => 'Excel, PDF or Word format (1.75MB or less)'])
                            <input type="file" name="file_support">
                        @endcomponent
                    @endslot
                    @if ($mode == 4)
                        @slot('questions')
                            @include('partials.question.index', ['questions' => $par->questions])
                        @endslot
                        @include('partials.par.advice')
                        @include('partials.par.vp')
                    @endif
                @endcomponent
                <div class="panel-footer text-right">
                    <input type="hidden" name="mode" value="{{ $mode }}">
                    <input type="hidden" name="project_id" value="{{ $project->id }}">
                    <button type="submit" class="btn btn-primary" name="save_draft" value="0">Submit</button>
                </div>
            </div>
        </form>
    @endif
@endsection

resources/views/par/index-project.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    @component('partials.breadcrumbs.project', ['project' => $project])
        <li class="active">PARs</li>
    @endcomponent
@endsection

@section('title')
  Program Alteration Requests (PARs)
@endsection

@section('content')
    <h3>{{ $project->project_name }}</h3>
    @if ($project->pars->count() == 0)
        <p>There are no PARs attached to this project.</p>
    @else
        @foreach ( $project->pars->sortByDesc('created_at') as $par )
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">PAR {{ $par->board_id }}</h3>
                </div>
                @component('partials.par.main', ['mode' => 4])
                    @slot('introduction')
                        <p>
                            Submitted: {{ formatDate($par->created_at) }}<br>
                            by NetID: {{ $par->netid }}
                        </p>
                    @endslot
                    @slot('changes')
                        <div class="well">{!! nl2br($par->changes) !!}</div>
                    @endslot
                    @slot('document')
                        <p>
                            @if (isset($par->fileSupportURL))
                                <a href="{{ $par->fileSupportURL }}">Supporting Document</a>
                            @else
                                No Document Attached
                            @endif
                        </p>
                    @endslot
                    @slot('questions')
                        @include('partials.question.index', ['questions' => $par->questions])                        
                    @endslot
                    @slot('advice')
                        @if (isset($par->advice))
                            <div class="well">{!! nl2br($par->advice) !!}</div>
                        @else  
                            <p>No advice available</p>
                        @endif
                    @endslot
                    @slot('approval')
                        <p>{{ formatBoolean($par->approved) }}</p>
                    @endslot
                    @slot('advice_document')
                        @if (isset($par->fileAdviceURL))
                            <a href="{{ $par->fileAdviceURL }}">Supporting Document</a>
                        @else
                            No Document Attached
                        @endif
                    @endslot
                    @slot('vp_comments')
                        @if (isset($par->vp_comments))
                            <div class="well">{!! nl2br($par->vp_comments) !!}</div>
                        @else  
                            <p>No comments available</p>
                        @endif
                    @endslot
                    @slot('vp_approval')
                        <p>{{ formatBoolean($par->vp_approved) }}</p>
                    @endslot
                @endcomponent
            </div>
        @endforeach
    @endif
@endsection

resources/views/par/index.blade.php
@php
$pars_array = [];
$years = [];

foreach ($pars as $key => $par){
    array_push($pars_array, $par);
    if(!in_array($par->project->start_year+1, $years)){
        array_push($years, $par->project->start_year+1);
    }
}


function cmp($a, $b)
{
    if($a->project->start_year == $b->project->start_year){ return 0 ; }
	return ($a->project->start_year > $b->project->start_year) ? -1 : 1;
}

usort($pars_array, "cmp");
arsort($years);
@endphp

@extends('layouts.app')

@section('breadcrumbs')
    @component('partials.breadcrumbs.default')
        <li class="active">PARs</li>
    @endcomponent
@endsection

@section('title')
  Program Alteration Requests (PARs)
@endsection

@section('content')
    <h4>Which group of PARs would you like to see?</h4>
    <div id="filter_wrap">
        <form id="status_filter" role="form" method="GET" action="{{ route('pars.admin.index', baseRouteParams()) }}">
            <div>
                <div>
                    @include('partials.form.filter_select', ['name' => 'par-status', 'label' => 'PAR Status', 'items' => $par_statuses])
                </div>
            </div>
        </form>
        <select name="fiscal_year" id="fiscal_year" class="form-control">
            <option disabled selected hidden value="Fiscal Year">Fiscal Year</option>
            <?php foreach($years as $year){ ?>
                <option value="<?=$year?>"><?= $year ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="table-responsive">
        <table class="table-dark table-hover table-striped table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Project ID</th>
                    <th>PAR ID</th>
                    <th>Applicant</th>
                    <th>Project Name</th>
                    <th>Fiscal Year</th>
                    <th>Board Approval</th>
                    <th>VP Approval</th>
                    <th>Date Submitted</th>
                    @if (userIsAdmin())
                        <th></th>
                        <th></th>
                        <th></th>
                    @endif
                    @if (userIsPower())
                        <th></th>
                        <th></th>
                    @endif
                    @if (userIsChair())
                        <th></th>
                    @endif
                </tr>
            </thead>
            <tbody id="pars_table_container">
            @foreach ($pars_array as $key => $par)
                <tr data-year="<?= $par->project->start_year + 1 ?>" class="show_row par_row">
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $par->project->board_id }}</td>
                    <td><a href="{{ route('pars.show', routeParams(['id' => $par->id])) }}">{{ $par->board_id }}</a></td>
                    <td>{{ $par->project->first_name }} {{ $par->project->last_name }}</td>
                    <td>{{ $par->project->project_name }}</td>
                    <td>{{ $par->project->start_year + 1 }}</td>
                    <td>{{ formatBoolean($par->approved) }}</td>
                    <td>{{ formatBoolean($par->vp_approved) }}</td>
                    <td>{{ formatDate($par->created_at) }}</td>
                    @if (userIsAdmin())
                        <td>
                            @if (isset($par->approved))
                                <span class="text-silver glyphicon glyphicon-question-sign">
                            @else
                                <a class="text-blue30w" href="#" title="Submit Question"
                                    data-toggle="modal"
                                    data-target="#modalQuestion"
                                    data-title="{{ $par->board_id }}"
                                    data-project="{{ $par->project->project_name }}"
                                    data-item-type="2"
                                    data-item-id="{{ $par->id }}">
                                    <span class="glyphicon glyphicon-question-sign">
                                </a>
                            @endif
                        </td>
                        <td>
                            @if (isset($par->approved))
                                <span class="text-silver glyphicon glyphicon-list-alt">
                            @else
                                <a class="text-blue30w" href="{{ route('pars.advice', routeParams(['id' => $par->id])) }}" title="Add Advice"><span class="glyphicon glyphicon-list-alt"></a>
                            @endif
                        </td>
                        <td>
                            @if (isset($par->vp_approved))
                                <span class="text-silver glyphicon glyphicon-ok-sign">
                            @else
                                <a class="text-blue30w" href="{{ route('pars.vp', routeParams(['id' => $par->id])) }}" title="VP Review"><span class="glyphicon glyphicon-ok-sign"></a>
                            @endif
                        </td>
                    @endif
                    @if (userIsPower())
                        <td><a class="text-blue30w" href="{{ route('pars.admin.edit', routeParams(['id' => $par->id])) }}" title="Edit Par"><span class="glyphicon glyphicon-pencil"></a></td>
                        <td>
                            <a href="#" class="text-blue30w" title="Delete Par"
                            data-toggle="modal"
                            data-target="#modalDelete"
                            data-title="PAR {{ $par->board_id }}"
                            data-action="{{ route('pars.destroy', routeParams(['id' => $par->id])) }}"
                            ><span class="glyphicon glyphicon-trash"></a>
                        </td>
                    @endif
                    <!-- Adding function for chairs to give advice -->
                    @if (userIsChair())
                        <td>
                        @if (isset($par->approved))
                                <span class="text-silver glyphicon glyphicon-list-alt">
                            @else
                                <a class="text-blue30w" href="{{ route('pars.advice', routeParams(['id' => $par->id])) }}" title="Add Advice"><span class="glyphicon glyphicon-list-alt"></a>
                            @endif
                        </td>
                    @endif
                </tr>
            @endforeach
            </tbody>
        </table>
        @if ($pars->count() == 0)
            <div class="alert alert-info" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <i aria-hidden="true" class="ua-brand-x"></i>
                </button>
                There were no results. Please try again.
            </div>
        @endif
    </div>
@endsection

@include('partials.question.create')
@include('partials.confirm_delete')

<script>
    NodeList.prototype.forEach = Array.prototype.forEach;

    document.addEventListener("DOMContentLoaded", function() {
        var el = document.getElementById('fiscal_year');
        el.addEventListener('change', function(e){
            document.querySelectorAll('.par_row').forEach(function(row){
                if(row.getAttribute('data-year') == el.options[el.selectedIndex].value){
                    if(!row.classList.contains('show_row')){
                        row.classList.add('show_row');
                    }
                }else{
                    if(row.classList.contains('show_row')){
                        row.classList.remove('show_row');
                    }
                }
            });
        });
    });
</script>

resources/views/par/view.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    @if ($mode > 1)
        @component('partials.breadcrumbs.par')
            <li class="active">{{ $mode == 4 ? $par->project->board_id : $title }}</li>
        @endcomponent
    @else
        @component('partials.breadcrumbs.base')
            <li><a href="{{ route('progress.start', baseRouteParams()) }}">PARs</a></li>
            <li class="active">{{ $par->project->board_id or $par->project->project_name }}</li>
        @endcomponent
    @endif
@endsection

@section('title')
    @if ($mode == 1)
        Submit PARs
    @elseif ($mode == 2)
        Submit Advice
    @else
        PAR Review
    @endif
@endsection

@section('content')
    <h3>
        @if ($mode == 2)
            PAR {{ $par->board_id }}
        @else
            {{ $par->project->project_name }}
        @endif
    </h3>

    @if ($review)
        @include('partials.alert.review', ['title' => $title])
    @endif

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">PAR Information</h3>
        </div>

        @component('partials.par.main', ['mode' => $mode])
            @slot('introduction') @endslot
            @slot('changes')
                <div class="well">{!! nl2br($par->changes) !!}</div>
            @endslot
            @slot('document')
                <p>
                    @if (isset($par->fileSupportURL))
                        <a href="{{ $par->fileSupportURL }}">Supporting Document</a>
                    @else
                        No Document Attached
                    @endif
                </p>
            @endslot
            @if ($mode == 4)
                @slot('questions')
                    @include('partials.question.index', ['questions' => $par->questions])
                @endslot
            @endif
            @if ($mode == 2 || $mode == 4)
                @slot('advice')
                    @if (isset($par->advice))
                        <div class="well">{!! nl2br($par->advice) !!}</div>
                    @else  
                        <p>No advice available</p>
                    @endif
                @endslot
                @slot('approval')
                    <p>{{ formatBoolean($par->approved) }}</p>
                @endslot
                @slot('advice_document')
                    @if (isset($par->fileAdviceURL))
                        <a href="{{ $par->fileAdviceURL }}">Supporting Document</a>
                    @else
                        No Document Attached
                    @endif
                @endslot
            @endif
            @if ($mode == 3 || $mode == 4)
                @slot('vp_comments')
                    @if (isset($par->vp_comments))
                        <div class="well">{!! nl2br($par->vp_comments) !!}</div>
                    @else  
                        <p>No comments available</p>
                    @endif
                @endslot
                @slot('vp_approval')
                    <p>{{ formatBoolean($par->vp_approved) }}</p>
                @endslot
            @endif
        @endcomponent
        @if ($review)
            <div class="panel-footer text-right">
                <a href="{{ route('pars.' . $edit_route, routeParams(['id' => $par->id])) }}" class="btn btn-default">Edit</a>
                <a href="{{ $submit_route }}" class="btn btn-primary submit-review">Submit Final Version</a>
            </div>
        @endif
    </div>
@endsection

resources/views/par/vp.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    @component('partials.breadcrumbs.par')
        <li class="active">VP Review</li>
    @endcomponent
@endsection

@section('title')
  VP Review
@endsection

@section('content')
    <h3>{{ $par->project->project_name }}</h3>
    <p>Use the form below to submit final comments and a decision for PAR {{ $par->board_id }}.</p>
    <p><strong>NOTE:</strong> For best results, please <strong>enter plain text</strong>. Pasting preformatted Word content may yield unpredictable results. If you already have formatted content in Word, try saving the Word document as plain text or copying the content into a plain text editor such as Notepad or TextEdit. Then copy/paste the plain text content into this form.</p>
    <p><strong>ALSO NOTE:</strong> these comments will be part of the original proposal's permanent record and <strong>will be viewable by the general public.</strong></p>

    <form role="form" method="POST" enctype="multipart/form-data" action="{{ route('pars.vp.update', routeParams(['id' => $par->id])) }}">
        {{ method_field('PUT') }}
        {{ csrf_field() }}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">VP Review Information</h3>
            </div>
            @component('partials.par.main', ['mode' => $mode])
                @include('partials.par.vp')
            @endcomponent
            <div class="panel-footer text-right">
                <input type="hidden" name="par_id" value="{{ $par->id }}">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection