routes/web.php
<?php

use App\Site;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// sites
Route::group(['prefix' => 'sites', 'as' => 'sites.'], function () {
  Route::post('{id}/files/save', 'SiteController@saveFiles')->name('files.save');
  Route::delete('{id}/files/{file_id}/delete', 'SiteController@deleteFile')->name('files.destroy');
  Route::post('{id}/departments/save', 'SiteController@saveDepartment')->name('departments.save');
  Route::delete('{id}/departments/{dept_id}/delete', 'SiteController@deleteDepartment')->name('departments.destroy');
  Route::post('{id}/initiatives/save', 'SiteController@saveInitiative')->name('initiatives.save');
  Route::put('{id}/initiatives/{init_id}/update', 'SiteController@updateInitiative')->name('initiatives.update');
  Route::delete('{id}/initiatives/{init_id}/delete', 'SiteController@deleteInitiative')->name('initiatives.destroy');
});
Route::resource('sites', 'SiteController');

// site specific routes
Route::group(['prefix' => '{site}'], function () {
  Route::get('/', 'SiteController@show')->name('index');
  Route::get('contact', 'SiteController@contact')->name('contact');
  Route::post('contact', 'SiteController@contactSend')->name('contact.send');
  Route::get('admin', 'SiteController@admin')->name('admin');

  // pages (editing)
  Route::put('pages/order', 'PageController@updateOrder')->name('pages.order');
  Route::resource('pages', 'PageController');

  // project sets
  Route::group(['prefix' => 'project-sets', 'as' => 'project-sets.'], function() {
    Route::get('{id}/set', 'ProjectSetController@setSession')->name('set');
  });
  Route::resource('project-sets', 'ProjectSetController');

  // questions and answers
  Route::post('{id}/extend', 'QuestionController@questionExtension')->name('questions.questionExtension');

  // Route::get('{id}/extend/done','QuestionController@questionExtensionDone');
  Route::resource('questions', 'QuestionController');

  Route::resource('answers', 'AnswerController');

  // users
  Route::resource('users', 'UserController');
  Route::put('users/site/update', 'UserController@updateSite')->name('users.site.update');
  Route::get('directory', 'UserController@directory')->name('users.directory');
  Route::group(['prefix' => 'board/apply'], function() {
    Route::get('/', 'UserController@apply')->name('users.apply');
    Route::post('/', 'UserController@applyStore')->name('users.apply.store');
    Route::get('index', 'UserController@applyIndex')->name('users.apply.index');
    Route::get('{id}/view', 'UserController@applyView')->name('users.apply.view');
    Route::get('{id}/confirm', 'UserController@confirm')->name('users.apply.confirm');
    Route::get('{id}/edit', 'UserController@applyEdit')->name('users.apply.edit');
    Route::put('{id}', 'UserController@applyUpdate')->name('users.apply.update');
    Route::put('{id}/save', 'UserController@applySave')->name('users.apply.save');
    Route::put('{id}/accept', 'UserController@applyAccept')->name('users.apply.accept');
    Route::delete('{id}/destroy', 'UserController@applyDestroy')->name('users.apply.destroy');
  });

  Route::group(['prefix' => '{project_set}'], function() {
    // custom project routes
    Route::group(['prefix' => 'projects', 'as' => 'projects.'], function () {
      Route::get('start', 'ProjectController@createStart')->name('start');
      Route::put('save', 'ProjectController@save')->name('save');
      Route::put('approve', 'ProjectController@approve')->name('approve');
      Route::get('review', 'ProjectController@review')->name('review');
      Route::get('admin', 'ProjectController@admin')->name('admin.index');
      Route::get('{id}/admin', 'ProjectController@adminEdit')->name('admin.edit');
      Route::get('{id}/confirm', 'ProjectController@confirm')->name('apply.confirm');
      Route::get('{id}/approve', 'ProjectController@showApprove')->name('apply.approve');
      Route::get('{id}/full', 'ProjectController@full')->name('full');
      Route::post('{id}/remind', 'ProjectController@remind')->name('remind');
      Route::get('{id}/files', 'ProjectController@files')->name('files');
      Route::post('{id}/files/save', 'ProjectController@saveFile')->name('files.save');
      Route::delete('files/{id}/delete', 'ProjectController@deleteFile')->name('files.destroy');
      Route::put('files/{id}/move', 'ProjectController@moveFile')->name('files.move');
      Route::get('{id}/revisions', 'ProjectController@revisions')->name('revisions');
      Route::get('{id}/budgets', 'ProjectController@budgets')->name('budgets');
      Route::get('{id}/notifications', 'ProjectController@notifications')->name('notifications');
      Route::get('{id}/questions', 'ProjectController@questions')->name('questions');
      Route::get('{id}/comments', 'ProjectController@comments')->name('comments');
      Route::post('{id}/comments/save', 'ProjectController@saveComment')->name('comments.save');
    });
    // project resource routes
    Route::resource('projects', 'ProjectController');

    // progress reports
    Route::group(['prefix' => 'progress', 'as' => 'progress.'], function() {
      Route::get('start', 'ProgressReportController@createStart')->name('start');
      Route::get('{id}/review', 'ProgressReportController@review')->name('review');
      Route::get('{id}/admin', 'ProgressReportController@adminEdit')->name('admin');
      Route::post('send', 'ProgressReportController@send')->name('send');
      Route::put('{id}/move', 'ProgressReportController@move')->name('move');
    });
    Route::resource('progress', 'ProgressReportController');

    // pars
    Route::group(['prefix' => 'pars', 'as' => 'pars.'], function() {
      Route::get('start', 'ParController@createStart')->name('start');
      Route::get('admin', 'ParController@admin')->name('admin.index');
      Route::get('{id}/review', 'ParController@review')->name('review');
      Route::get('{id}/advice', 'ParController@advice')->name('advice');
      Route::put('{id}/advice/update', 'ParController@updateAdvice')->name('advice.update');
      Route::get('{id}/advice/review', 'ParController@reviewAdvice')->name('advice.review');
      Route::get('{id}/vp', 'ParController@vp')->name('vp');
      Route::put('{id}/vp/update', 'ParController@updateVp')->name('vp.update');
      Route::get('{id}/vp/review', 'ParController@reviewVp')->name('vp.review');
      Route::get('{id}/approve', 'ParController@approve')->name('approve');
      Route::get('{id}/admin/edit', 'ParController@adminEdit')->name('admin.edit');
    });
    Route::resource('pars', 'ParController');
  });

  // login
  Route::get('login', 'UserController@login')->name('login');

  // handle redirects from webauth
  Route::get('webauth/redirect', ['as' => 'guest.login.redirect', 'uses' => 'WebauthController@redirect']);

  // this goes last to not catch anything important
  Route::get('/{any}', 'PageController@showBySlug')->where('any', '.*');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'student_id',
        'phone',
        'email',
        'address',
        'city',
        'state',
        'zip',
        'club_org_1',
        'club_org_2',
        'club_org_3',
        'club_org_4',
        'user_title_id',
        'text',
        'user_standing_id',
        'user_type_id',
        'user_status_id',
        'responsibilities',
        'netid',
        'role_id',
        'start_year',
        'fiscal_year',
        'directory',
        'par_contact',
        'question_contact',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // get the role this user has
    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    // get the status of this user
    public function status()
    {
        return $this->belongsTo('App\UserStatus', 'user_status_id');
    }

    // get the standing for this user
    public function standing()
    {
        return $this->belongsTo('App\UserStanding', 'user_standing_id');
    }

    // get the title of this user
    public function title()
    {
        return $this->belongsTo('App\UserTitle', 'user_title_id');
    }

    // get the type of this user
    public function type()
    {
        return $this->belongsTo('App\UserType', 'user_type_id');
    }

    // get the applications belonging to this user
    public function applications()
    {
        return $this->hasMany('App\UserApplication');
    }

    // get the sites associated with this user
    public function sites()
    {
        return $this->belongsToMany('App\Site');
    }

    // check if the user is an admin
    public function isAdmin()
    {
        return $this->role->id == 4;
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    // clean up relations before deleting
    public function delete()
    {
        $this->applications()->delete();
        Parent::delete();
    }
}

app/UserType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
    // get the users with this type
    public function users()
    {
        return $this->hasMany('App\User');
    }
}

resources/views/partials/user/apply.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Academic Information</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                {{ $academic_information_left }}
            </div>
            <div class="col-md-6">
                {{ $academic_information_right }}
            </div>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Time Commitments</h3>
    </div>
    <div class="panel-body horizontal-reset">
        {{ $time_commitments }}
    </div>
</div>
{{ $clubs_orgs }}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Qualifications</h3>
    </div>
    <div class="panel-body">
        <div class="horizontal-reset">
            {{ $qualifications }}
            <br>
            <p><strong>Please attach a resume to this application</strong></p>
            {{ $resume }}
        </div>
        <br>
        <p><strong>Please list two references we may contact</strong></p>
        <div class="row">
            <div class="col-md-6">
                {{ $references_left }}
            </div>
            <div class="col-md-6">
                {{ $references_right }}
            </div>
        </div>
    </div>
</div>
<div class="panel panel-default">
<div class="panel-heading">
    <h3 class="panel-title">Terms and Conditions</h3>
</div>
<div class="panel-body">
    <p>By checking the box below and submitting this application, I understand that my name, class and major can be used in publications; that I will abide by any adopted governing documents, and that all information provided is accurate.</p>
    {{ $terms }}
</div>
</div>

resources/views/partials/user/clubs-form.blade.php
@component('partials.user.clubs')
    @slot('clubs_orgs_intro')
        @if (isset($clubs_orgs_intro))
            {{ $clubs_orgs_intro }}
        @endif
    @endslot
    @slot('clubs_orgs_left')
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'club_org_1', 'label' => 'Club/Org #1'])
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'club_org_2', 'label' => 'Club/Org #2'])
    @endslot
    @slot('clubs_orgs_right')
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'club_org_3', 'label' => 'Club/Org #3'])
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'club_org_4', 'label' => 'Club/Org #4'])
    @endslot
@endcomponent

resources/views/partials/user/clubs.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Clubs &amp; Organizations</h3>
    </div>
    <div class="panel-body">
        {{ $clubs_orgs_intro }}
        <div class="row">
            <div class="col-md-6">
                {{ $clubs_orgs_left }}
            </div>
            <div class="col-md-6">
                {{ $clubs_orgs_right }}
            </div>
        </div>
    </div>
</div>

resources/views/partials/user/contact-form.blade.php
@component('partials.user.contact')
    @slot('contact_information_left')
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'first_name', 'label' => 'First Name'])
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'last_name', 'label' => 'Last Name'])
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'student_id', 'label' => 'Student ID'])
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'phone', 'label' => 'Phone'])
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'email', 'label' => 'Email'])
    @endslot
    @slot('contact_information_right')
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'address', 'label' => 'Address'])
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'city', 'label' => 'City'])
        @include('partials.form.select', ['inline' => true, 'name' => 'state', 'label' => 'State', 'items' => $states, 'value_as_key' => true])
        @include('partials.form.text', ['inline' => true, 'type' => 'text', 'name' => 'zip', 'label' => 'Zip Code'])
    @endslot
@endcomponent

resources/views/partials/user/contact.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Contact Information</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                {{ $contact_information_left }}
            </div>
            <div class="col-md-6">
                {{ $contact_information_right }}
            </div>
        </div>
    </div>
</div>

resources/views/partials/user/index.blade.php
<div class="table-responsive">
    <table class="table-dark table-hover table-striped table-condensed">
        <thead>
            <tr>
                @if(!$directory)
                    <th>#</th>
                @endif
                <th>Name</th>
                @if(!$directory)
                    <th>Start Year</th>
                    <th>Fiscal Year</th>
                    <th>Status</th>
                @endif
                <th>Title</th>
                @if(!$directory)
                    <th>Type</th>
                    <th>Access Level</th>
                    <th>Directory</th>
                    <th></th>
                    <th></th>
                @endif
                @if($directory)
                    @if($admin)
                        <th>Membership Type</th>
                    @else
                        <th>Class</th>
                    @endif
                    <th>Responsibilities</th>
                @endif
            </tr>
        </thead>
        <tbody>
        @foreach ($users as $user)
            <tr>
                @if(!$directory)
                    <td>{{ $loop->iteration }}</td>
                @endif
                <td>{{ $user->full_name }}</td>
                @if(!$directory)
                    <td>{{ $user->start_year }}</td>
                    <td>{{ $user->fiscal_year > 0 ? $user->fiscal_year : '' }}</td>
                    <td>{{ $user->status['attributes']['name'] }}</td>
                @endif
                <td>{{ (empty($user->user_title_id) || $user->user_title_id == 8) ? $user->title_other : $user->title->name }}</td>
                @if(!$directory)
                    <td>{{ $user->type->name or '' }}</td>
                    <td>{{ $user->role->name }}</td>
                    <td>{{ formatBoolean($user->directory) }}</td>
                    <td><a class="text-blue30w" href="{{ route('users.edit', ['site' => site()->slug, 'id' => $user->id]) }}" title="Edit Board Member"><span class="glyphicon glyphicon-pencil"></a></td>
                    <td>
                        <a href="#" class="text-blue30w" title="Delete Board Member"
                        data-toggle="modal"
                        data-target="#modalDelete"
                        data-title="{{ $user->full_name }}"
                        data-action="{{ route('users.destroy', ['site' => site()->slug, 'id' => $user->id]) }}"
                        ><span class="glyphicon glyphicon-trash"></a>
                    </td>
                @endif
                @if($directory)
                    @if($admin)
                        <td>{{ $user->type->name }}</td>
                    @else
                        <td>{{ $user->standing->name or ''}}</td>
                    @endif
                    <td>{{ $user->responsibilities }}</td>
                @endif
            </tr>
        @endforeach
        </tbody>
    </table>
</div>